services:
  dapper-api:
    build: .
    ports:
      - "5024:8080"
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
      - "1433:1433"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CrudApi;User=sa;Password=Sqlserver0001&;
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Sqlserver0001&
    volumes:
      - sqlserver-data:/var/opt/mssql/data
      - ./dapper-api/scripts/dbo_init.sql:/tmp/dbo_init.sql
volumes:
  sqlserver-data:
