# services:
#   dapper-api:
#     build: .
#     ports:
#       - "5024:8080"
#     depends_on:
#       - sqlserver
#   sqlserver:
#     image: mcr.microsoft.com/azure-sql-edge:latest
#     command: /opt/mssql/bin/sqlservr
#     volumes:
#       - sqlserver-data:/var/opt/mssql/data
#       - ./dapper-api/scripts/dbo_init.sql:/tmp/dbo_init.sql
#       - /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 30 && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Sqlserver0001&' -d master -i /tmp/dbo_init.sql"    
#     user: root
#     ports:
#       - "1433:1433"
#     environment:
#       - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CrudApi;User Id=sa;Password=Sqlserver0001&;Encrypt=false;
#       - ACCEPT_EULA=Y
#       - MSSQL_SA_PASSWORD=Sqlserver0001&
#     # command:
#     #   - /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 30 && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Sqlserver0001&' -d CrudApi -i /tmp/dbo_init.sql"
#   # sqlcmd:
#   #   image: mcr.microsoft.com/mssql-tools:latest
#   #   command: /opt/mssql_scripts/dbo_init.sql
#   #   user: root
#   #   stdin_open: true
#   #   volumes:
#   #     - ./dapper-api/scripts/dbo_init.sql:/opt/mssql_scripts/dbo_init.sql
# volumes:
#   sqlserver-data:

services:
  dapper-api:
    build: .
    ports:
      - "5024:8080"
    depends_on:
      - sqlserver
  sqlcmd:
    image: mcr.microsoft.com/mssql-tools:latest
    user: root
    stdin_open: true
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    volumes:
      - sqlserver-data:/var/opt/mssql/data
    user: root
    ports:
      - "1433:1433"
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - ConnectionStrings__AZURE_SQL_CONNECTIONSTRING=${AZURE_SQL_CONNECTIONSTRING}
volumes:
  sqlserver-data: